# Generated by Django 4.2.16 on 2024-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_userprofile_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
