# Generated by Django 4.2.16 on 2024-11-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_userprofile_data_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Usuário Profile', 'verbose_name_plural': 'Usuário Profiles'},
        ),
    ]
